### ISSUE TITLE
container image on ghcr.io is unauthorized to public pulls

### ISSUE THREAD

**Issue by kbroughton** [praetorian-inc/snowcat#29]
docker pull ghcr.io/praetorian-inc/snowcat:latest
Error response from daemon: Head "https://ghcr.io/v2/praetorian-inc/snowcat/manifests/latest": unauthorized

**Comment by amlweems** [comment]
Thanks @kbroughton! We've just marked it as public, can you try pulling the image again?

**Comment by kbroughton** [comment]
fxed, you may close. Thanks!
